/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.examples.oauth2connectorexample;

import org.junit.Assert;
import org.junit.Test;


public class Oauth2ExampleConnectorTest {
	
	@Test
	public void dummyTest() {
		Assert.assertTrue(true);
	}
}
